server:
    port: 1800
spring:
   rabbitmq:
        host: localhost
        port: 5672
        username: gest
        password: gest
        virtual-host: /mq
   cloud:
      stream:
        bindings:
          PRODUCER_CHANNEL:
               destination: vane_mq
               contentType: application/json
debug: true