server:
    port: 1700
spring:
   rabbitmq:
        host: localhost
        port: 5672
        username: gest
        password: gest
        virtual-host: /mq
   cloud:
      stream:
        bindings:
          CONSUMER_CHANNEL:
              destination: vane_mq
              contentType: application/json
              group: vane_mq_group
debug: true



